name: 即创视频生成 (Jichuang Video Generation)

# 当收到一个类型为 'generate-video' 的 repository_dispatch 事件时触发
on:
  repository_dispatch:
    types: [generate-video]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    # 定义 job 的输出
    outputs:
      task_name: ${{ steps.run_script.outputs.task_name }}

    steps:
      - name: Checkout repository
        # 此步骤会下载你的仓库代码，包括 run_automation.py 和 即创.json
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright openai

      - name: Install Playwright Browsers
        # --with-deps 会安装所有必需的操作系统依赖
        run: playwright install --with-deps

      - name: Run Python script
        id: run_script
        env:
          # 我们只需要传递这两个环境变量
          MODELSCOPE_API_KEY: ${{ secrets.MODELSCOPE_API_KEY }}
          CUSTOM_TEXT: ${{ github.event.client_payload.text }}
          # GITHUB_OUTPUT 是一个特殊的文件路径，用于设置步骤的输出
          GITHUB_OUTPUT: ${{ steps.run_script.outputs.task_name }}
        run: python run_automation.py

      - name: Upload artifacts
        # 无论成功或失败，都上传截图以便调试
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generation-artifacts
          path: |
            *.png
